### ISSUE TITLE
Menu and view not loaded when using the classic 'signin' method

### ISSUE THREAD

**Issue by fjouatte** [anybox/odoo-auth#1]
This is not a common case but this is pretty annoying when you meet it. When you use the #login,password signin way it causes a little bug if the user you're trying to connect with is from a group which has only one allowed menu to see.

Menu's items and view are not loaded, you have to get rid of the '#login,password' part of the url after the success of the connection to finally show the view.

**Comment by petrus-v** [comment]
interesting, we have quite the same matter with multiple menu too, I guess #2 is about fixing that.
